[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
name = "pycqed"
version = "0.1.0"
description = "Python-based circuit QED data acquisition framework"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Quantum Device Laboratory"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "func-timeout",
    "lmfit",
    "matplotlib",
    "more-itertools",
    "neupy",
    "nlopt",
    "numpy",
    "pandas",
    "pyqtgraph",
    "pyside2",
    "qcodes",
    "qcodes-loop",
    "qutip",
    "requests",
    "scikit-learn",
    "scipy",
    "sympy",
    "tensorflow",
    "zhinst",
]

[project.optional-dependencies]
docs = [
    "myst-parser",
    "sphinx",
    "sphinx-rtd-theme",
]
linting = [
    "pylint",
]
measurement_setup = [
    "influxdb",
    "nidaqmx",
    "pyvisa",
    "pyserial",
    "zhinst-hdiq",
    "zhinst-qcodes",
]
user = [
    "cython",
    "jupyter",
    "jupyter-contrib-nbextensions",
    "psutil",
    "plotly",
    "pyyaml",
]

[tool.setuptools.packages.find]
where = ["./"]

[tool.setuptools.package-data]
pycqed = [
    "utilities/WARNING.png",
]
